### ISSUE TITLE
Zaproszenie do współpracy

### ISSUE THREAD

**Issue by martab0** [katgaj/markdown_intro#1]
W tej chwili widzę zawartość Twego repozytorium, bo jest publiczne. Proszę nadaj mi też dostęp (Invite collaborator) na wypadek gdyby było w przyszłości prywatne :-)

**Comment by katgaj** [comment]
Dobrze, ogarnę to po pracy, albo w weekend

wt., 21 lis 2023, 22:54 użytkownik martab0 ***@***.***>
napisał:

**Comment by martab0** [comment]
Udało się :-)

**Comment by katgaj** [comment]
😊

**Comment by katgaj** [comment]
cześć, podziałałam z emoji (zainstalowałam rozszerzenie :emojisense:), porobiłam wyrównania w tabeli, jest przekreślenie.
a jak zrobić ten obrazek z dymkiem? gdzie szukać info na ten temat? i ten inny sposób zapisywania wzorów? nie wiem, czy wiem, o co chodzi. przejrzałam basic i extended syntax na https://www.markdownguide.org/ i nie mam pomysłu🤔 ogólnie zabawa przednia. pozdrawiam

**Comment by martab0** [comment]
Super wyszło z emoji, z tabelą i z przekreśleniem :)

**Comment by katgaj** [comment]
Dzięki za wskazówki 🤩 poćwiczę


niedz., 26 lis 2023, 17:38 użytkownik martab0 ***@***.***>
napisał:
